# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Pharmacy.create(name: "チューリップ薬局",postcode: "1638001",prefecture_code: "東京都",address_city: "新宿区2丁目",address_street: "8-1",address_building: "",normal_telephone_number: "0353211111",abnormal_telephone_number: "01011112222",remarks: "元気で明るい薬局作りを心がけています。",opinion: "アプリケーションに◯◯できる機能を追加して欲しい",email: "tulips@gmail.com",password: "111111")
Pharmacy.find(1).activities.create(week_day: "monday",business: "open",open: "09:00",close: "18:00")
Pharmacy.find(1).activities.create(week_day: "tuesday",business: "open",open: "09:00",close: "18:00")
Pharmacy.find(1).activities.create(week_day: "wednesday",business: "open",open: "09:00",close: "14:00")
Pharmacy.find(1).activities.create(week_day: "thursday",business: "open",open: "09:00",close: "18:00")
Pharmacy.find(1).activities.create(week_day: "friday",business: "open",open: "09:00",close: "18:00")
Pharmacy.find(1).activities.create(week_day: "saturday",business: "open",open: "09:00",close: "14:00")
Pharmacy.find(1).activities.create(week_day: "sunday",business: "close",open: "",close: "")
Pharmacy.create(name: "カーネーション薬局",postcode: "2608667",prefecture_code: "千葉県",address_city: "千葉市中央区市場町",address_street: "1-1",address_building: "",normal_telephone_number: "0432232110",abnormal_telephone_number: "01011113333",remarks: "GW中は◯月×日が休日当番となっており、開局時間は09:00〜18:00です。",opinion: "◯◯機能のデザインがイマイチ、改善して欲しい",email: "carnation@gmail.com",password: "111111")
Pharmacy.find(2).activities.create(week_day: "monday",business: "open",open: "10:00",close: "19:00")
Pharmacy.find(2).activities.create(week_day: "tuesday",business: "open",open: "10:00",close: "19:00")
Pharmacy.find(2).activities.create(week_day: "wednesday",business: "open",open: "10:00",close: "19:00")
Pharmacy.find(2).activities.create(week_day: "thursday",business: "close",open: "",close: "")
Pharmacy.find(2).activities.create(week_day: "friday",business: "open",open: "10:00",close: "19:00")
Pharmacy.find(2).activities.create(week_day: "saturday",business: "open",open: "10:00",close: "19:00")
Pharmacy.find(2).activities.create(week_day: "sunday",business: "open",open: "10:00",close: "14:00")
Pharmacy.create(name: "バラ薬局",postcode: "3309301",prefecture_code: "埼玉県",address_city: "さいたま市浦和区高砂3丁目",address_street: "15-1",address_building: "",normal_telephone_number: "0488242111",abnormal_telephone_number: "01011114444",remarks: "駐車場は普通車乗用車3台分のスペースを設けております。",opinion: "◯◯機能を使って××を使用としたらエラーが発生、改善して欲しい",email: "rose@gmail.com",password: "111111")
Pharmacy.find(3).activities.create(week_day: "monday",business: "open",open: "08:30",close: "19:00")
Pharmacy.find(3).activities.create(week_day: "tuesday",business: "open",open: "08:30",close: "19:00")
Pharmacy.find(3).activities.create(week_day: "wednesday",business: "open",open: "08:30",close: "19:00")
Pharmacy.find(3).activities.create(week_day: "thursday",business: "open",open: "08:30",close: "14:00")
Pharmacy.find(3).activities.create(week_day: "friday",business: "open",open: "08:30",close: "19:00")
Pharmacy.find(3).activities.create(week_day: "saturday",business: "open",open: "08:30",close: "19:00")
Pharmacy.find(3).activities.create(week_day: "sunday",business: "close",open: "",close: "")
Pharmacy.create(name: "ポインセチア薬局",postcode: "0308570",prefecture_code: "青森県",address_city: "青森市長島1丁目",address_street: "1-1",address_building: "",normal_telephone_number: "0177221111",abnormal_telephone_number: "01011115555",remarks: "日曜日も14:00まで開局しております。",opinion: "◯◯ページの××の色がとても見づらい、他の色に変えて欲しい",email: "poinsechia@gmail.com",password: "111111")
Pharmacy.find(4).activities.create(week_day: "monday",business: "open",open: "08:30",close: "20:00")
Pharmacy.find(4).activities.create(week_day: "tuesday",business: "open",open: "08:30",close: "20:00")
Pharmacy.find(4).activities.create(week_day: "wednesday",business: "open",open: "08:30",close: "20:00")
Pharmacy.find(4).activities.create(week_day: "thursday",business: "open",open: "08:30",close: "20:00")
Pharmacy.find(4).activities.create(week_day: "friday",business: "open",open: "08:30",close: "20:00")
Pharmacy.find(4).activities.create(week_day: "saturday",business: "open",open: "08:30",close: "20:00")
Pharmacy.find(4).activities.create(week_day: "sunday",business: "open",open: "08:30",close: "14:00")
User.create(admin: "1",name: "山田太郎",postcode: "1120004",prefecture_code: "東京都",address_city: "文京区1丁目",address_street: "3-6-1",address_building: "東京ドーム101号室",telephone_number: "0358009999",age: "36",sex: "male",body_weight: "",blood_types: "type_a",side_effect: "なし",allergy: "なし",sick: "なし",operation: "なし",remarks: "平日日中は仕事中の為、電話には出られません。",opinion: "たまにしか使わないから、パスワード忘れちゃうな・・・",email: "yamada_taro@gmail.com",password: "222222")
User.find(1).conditions.create(record_time: "#{Date.today}",systolic_blood_pressure: "107",diastolic_blood_pressure: "64",pulse: "72",blood_sugar: "69",attached_comment: "今日の健康診断の結果",updated_at: "#{Date.today}")
User.create(admin: "0",name: "高橋蓮",postcode: "9030815",prefecture_code: "沖縄県",address_city: "那覇市那覇市首里金城町1丁目",address_street: "wednesday",address_building: "首里城301号室",telephone_number: "0988862020",age: "5",sex: "male",body_weight: "18",blood_types: "type_o",side_effect: "なし",allergy: "ハウスダスト、花粉症",sick: "アトピー性皮膚炎",operation: "なし",remarks: "粉薬は苦手",opinion: "よく使ってるよ",email: "takahashi_ren@gmail.com",password: "222222")
User.create(admin: "0",name: "鈴木花子",postcode: "2790031",prefecture_code: "千葉県",address_city: "浦安市舞浜1丁目",address_street: "1",address_building: "ディズニーランド201号室",telephone_number: "0570008632",age: "85",sex: "female",body_weight: "38",blood_types: "type_b",side_effect: "アムロジピンでふらつき",allergy: "ペニシリン系で薬疹",sick: "52歳でリウマチ",operation: "64歳で胃全摘",remarks: "たまに薬を飲み忘れます",opinion: "手帳を持ち運ぶ必要が無くなり、とても助かっております",email: "suzuki_hanako@gmail.com",password: "222222")
User.find(3).conditions.create(record_time: "#{Date.today-7}",systolic_blood_pressure: "123",diastolic_blood_pressure: "102",pulse: "52",blood_sugar: "110",attached_comment: "孫と遊んだ",updated_at: "#{Date.today-7}")
User.find(3).conditions.create(record_time: "#{Date.today-6}",systolic_blood_pressure: "159",diastolic_blood_pressure: "120",pulse: "67",blood_sugar: "152",attached_comment: "今日はかかりつけの通院日、検査値が良くないと先生に怒られた",updated_at: "#{Date.today-6}")
User.find(3).conditions.create(record_time: "#{Date.today-5}",systolic_blood_pressure: "111",diastolic_blood_pressure: "93",pulse: "66",blood_sugar: "102",attached_comment: "今日は体調が良い",updated_at: "#{Date.today-5}")
User.find(3).conditions.create(record_time: "#{Date.today-4}",systolic_blood_pressure: "145",diastolic_blood_pressure: "111",pulse: "62",blood_sugar: "106",attached_comment: "今日は寒い",updated_at: "#{Date.today-4}")
User.find(3).conditions.create(record_time: "#{Date.today-3}",systolic_blood_pressure: "120",diastolic_blood_pressure: "97",pulse: "71",blood_sugar: "180",attached_comment: "どら焼き食べた",updated_at: "#{Date.today-3}")
User.find(3).conditions.create(record_time: "#{Date.today-2}",systolic_blood_pressure: "115",diastolic_blood_pressure: "92",pulse: "72",blood_sugar: "131",attached_comment: "天気が悪くて洗濯物が乾かない",updated_at: "#{Date.today-2}")
User.find(3).conditions.create(record_time: "#{Date.today-1}",systolic_blood_pressure: "125",diastolic_blood_pressure: "104",pulse: "52",blood_sugar: "123",attached_comment: "今日は買い物で昆布を買うのを忘れた",updated_at: "#{Date.today-1}")
User.find(3).conditions.create(record_time: "#{Date.today}",systolic_blood_pressure: "109",diastolic_blood_pressure: "82",pulse: "60",blood_sugar: "105",attached_comment: "今日は◯◯公園へ向かい30分散歩した",updated_at: "#{Date.today}")